# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: EPS@DEODE Working Week June 2025
author: "Martin Frølund"
email: "maf@dmi.dk"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off


# Information about where the book exists on the web
repository:
  url: https://github.com/mafdmi/EPS-DEODE-Working-Week-June2025
  branch: gh-pages  # Which branch of the repository should be used when creating links (optional)

exclude_patterns: [".venv", "*.toml", ".github", "README.md"]

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  config:
    nb_merge_streams: true
    nb_remove_code_source: true